site_name: Spytula
theme:
  name: material
  palette:
    - media: "(prefers-color-scheme: light)"
      scheme: spytula-light
      toggle:
        icon: octicons/moon-16
        name: "Switch to dark theme"
    - media: "(prefers-color-scheme: dark)"
      scheme: spytula-dark
      toggle:
        icon: octicons/sun-16
        name: "Switch to light theme"
  features:
    - content.tabs.link
    - announce.dismiss
    - content.code.copy
    - navigation.footer
    - navigation.top
    - search.highlight
    - search.share
    - search.suggest
    - toc.follow
  icon:
    logo: material/chef-hat
  favicon:
extra_css:
  - stylesheets/extra.css
nav:
  - Home: index.md
  - API Reference: api.md
  - Usage: usage.md
  - Contributing: contributing.md
plugins:
  - search
  - exclude:
      glob:
      - __pycache__/*
  - mkdocstrings:
      handlers:
        python:
          paths: [.]
          options:
            show_source: false
            separate_signature: true
            filters: ["!^_"]
            docstring_options:
              ignore_init_summary: true
            merge_init_into_class: true
markdown_extensions:
  - tables
  - toc:
      permalink: true
      title: Page contents
  - codehilite:
      guess_lang: false
  - admonition
  - pymdownx.details
  - pymdownx.superfences
  - pymdownx.highlight
  - pymdownx.extra
  - pymdownx.emoji:
      emoji_index: !!python/name:materialx.emoji.twemoji
      emoji_generator: !!python/name:materialx.emoji.to_svg
  - pymdownx.tabbed:
      alternate_style: true
      